import {
  LayoutDashboard,
  Users,
  UserSquare2,
  Package,
  Tags,
  Bird,
  FileText,
  CalendarCheck,
  ShoppingCart,
  Receipt,
  Wallet,
  CreditCard,
  Boxes,
  Truck,
  ReceiptText,
  Banknote,
  BarChart3,
  ScrollText,
  Settings,
  type LucideIcon,
} from "lucide-react";
import type { ModuleKey } from "@/lib/permissions";
import { MODULE_LABELS } from "@/lib/permissions";

export const MODULE_ROUTES: Record<ModuleKey, string> = {
  dashboard: "/dashboard",
  users: "/users",
  customers: "/customers",
  products: "/products",
  pricing: "/pricing",
  poultry: "/poultry",
  quotations: "/quotations",
  bookings: "/bookings",
  sales: "/sales",
  invoices: "/invoices",
  payments: "/payments",
  credit: "/credit",
  inventory: "/inventory",
  purchases: "/purchases",
  expenses: "/expenses",
  cash: "/cash",
  reports: "/reports",
  "audit-logs": "/audit-logs",
  settings: "/settings",
};

export const MODULE_ICONS: Record<ModuleKey, LucideIcon> = {
  dashboard: LayoutDashboard,
  users: Users,
  customers: UserSquare2,
  products: Package,
  pricing: Tags,
  poultry: Bird,
  quotations: FileText,
  bookings: CalendarCheck,
  sales: ShoppingCart,
  invoices: Receipt,
  payments: Wallet,
  credit: CreditCard,
  inventory: Boxes,
  purchases: Truck,
  expenses: ReceiptText,
  cash: Banknote,
  reports: BarChart3,
  "audit-logs": ScrollText,
  settings: Settings,
};

export const NAV_ORDER: ModuleKey[] = [
  "dashboard",
  "customers",
  "products",
  "pricing",
  "poultry",
  "quotations",
  "bookings",
  "sales",
  "invoices",
  "payments",
  "credit",
  "inventory",
  "purchases",
  "expenses",
  "cash",
  "reports",
  "users",
  "audit-logs",
  "settings",
];

export { MODULE_LABELS };
